# 修改端口号多次启动
server:
  port: 8763

# spring.application.name很重要，服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/