server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://localhost:8881?name=test
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            # 用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
            key-resolver: '#{@hostAddrKeyResolver}'
            # 令牌桶每秒填充平均速率
            redis-rate-limiter.replenishRate: 1000
            # 令牌桶总容量
            redis-rate-limiter.burstCapacity: 10000
  application:
    name: gateway-limiter
  redis:
    host: 47.98.213.18
    port: 6379
    database: 0
    username: root
    password: 123456