server:
  port: 8765

# spring.application.name很重要，服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# 负载均衡器通过eureka的注册列表中的服务实例。关掉eureka,负载均衡器也可以通过自身配置来负载均衡
# stores:
#  ribbon:
#    listOfService: example.com,google.com

# 指定服务进行负载均衡
eureka-client:
  ribbon:
    # 基于配置文件形式的 针对单个服务的 Ribbon 负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule



